name: grabber
description: "Flutter app to download videos and audios from youtube"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  injectable: ^2.5.0
  get_it: ^8.0.3
  retrofit: ^4.5.0
  logger: ^2.6.0
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4
  google_fonts: ^6.2.1
  flutter_bloc: ^9.1.1
  pretty_dio_logger: ^1.4.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  file_picker: ^10.2.0
  lottie: ^3.3.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner:
  injectable_generator:
  json_serializable:
  retrofit_generator:

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/animations/
