name: grabber
description: "Flutter app to download videos and audios from youtube"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  injectable_generator: ^2.7.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
